

parameters:
  - name: DebugMode
    displayName: Run the Pipeline in Debug Mode
    type: boolean
    default: false


variables:
  - name: System.Debug
    value: ${{ parameters.DebugMode }}


trigger:
- main


stages:
  - stage: EnvAndTests
    displayName:  'Tests'
    jobs:
    - job: requirements
      displayName: Install Requirements
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.10'
        displayName: Setting up Python

      - bash: pip install -r requirements.txt
        displayName: 'Installing pip requirements' 

      - script: |
          cd tests
          coverage run -m pytest testMockPerson.py
        displayName: 'Testing'
        

